services:
  nginx:
    image: nginx:alpine
    container_name: nginx_server
    ports:
      - "9000:9000"
    volumes:
      - ./data/nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - ctf_chals_network

  manager:
    build: ./manager-app
    ports:
      - "8002:5000"
    volumes:
      - ./data:/data
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always
    networks:
      - ctf_chals_network

networks:
  ctf_chals_network:
    external: true
